<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Common\NutrientMeasurement\MicroNutrients\Vitamins\VitaminBComplexes\VitaminB2.cs" />
    <None Include="Common\NutrientMeasurement\MicroNutrients\Vitamins\VitaminBComplexes\VitaminB9.cs" />
    <None Include="Common\NutrientMeasurement\MicroNutrients\Vitamins\VitaminBComplexes\VitaminB7.cs" />
  </ItemGroup>

</Project>
